import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

function Headline(){
	return (
		<Head>
			<title>JG Homepage</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	)
}

function Titles(){
	return(
		<h1 className={styles.title}>
			<a href="https://nextjs-six-kappa-95.vercel.app">JaeGeun</a>
		</h1>
	)
}

function SearchBar(props){
	function Docu() {
		if (props.clicks === styles.introduce) {
			return (
				<span>
					안녕하세요. 저는 장재근입니다.<br/>
					현재 AI 개발쪽으로 공부중입니다.<br/>
					이게 저의 첫 홈페이지가 되겠군요 <br/>
					잘부탁드립니다! <br/>
				</span>
			)
		}
		else {
			return (
				<span>
					<hr/>
					Language<br/><hr/>
					Python<br/>
					C<br/>
					C++<br/>
					JavaScript<br/>
					<hr/><br/><hr/>
					FrameWork<br/><hr/>
					Tensorflow<br/>
					Pytorch<br/>
					React<br/>
					<hr/>
				</span>
			)
		}
	}

	return(
		<div className={props.clicks}>
			<a href="#" onClick={(event)=>{
				event.preventDefault();
				props.onChangeMode();
				props.onChangeList();
			}}>
				<div className={props.lists}>
					<Docu></Docu>
				</div>
			</a>
		</div>
	)
	
}


function PrintIcons(props){
	if (props.click == styles.introduce){
		return (
			<div className={styles.iconarea}>
				<div className={styles.icons}>
					<a href="https://github.com/JaeGeunJang">
							<figure>
							<Image src="/github.svg" alt="Github Logo" 
							width={50} height={50} />
							<figcaption>github</figcaption>
							</figure>
					</a>
				</div>
	
				<div className={styles.icons}>
					<a href="https://jk-codingbeginner.tistory.com/">
						<figure>
							<Image src="/tistory.svg" alt="Tistory Logo" 
							width={50} height={50} />
							<figcaption>tistory</figcaption>
						</figure>
					</a>
				</div>
	
				<div className={styles.icons}>
					<a href="https://www.instagram.com/slow._.turtle/">
						<figure>
							<Image src="/insta.svg" alt="insta Logo" 
							width={50} height={50} />
							<figcaption>Insta</figcaption>
						</figure>
					</a>
				</div>
	
				<div className={styles.icons}>
					<a href="https://www.facebook.com/jaekeun95/">
						<figure>
							<Image src="/facebook.svg" alt="FB Logo" 
							width={50} height={50} />
							<figcaption>Fb</figcaption>
						</figure>
					</a>
				</div>
			</div>
		)
	}
	
}

export default function Home() {
	const [clicks, clickc] = useState(styles.introduce)
	const [lists, clists] = useState(styles.scroller)
	
	return (
		<div className={styles.container}>
			<a href="#" onClick={(event)=>{
			event.preventDefault();
			if (clicks===styles.introduce_click)
				{clickc(styles.introduce); clists(styles.scroller)}}} className={styles.clickarea}>
			
			<Headline></Headline>
				<main className={styles.main}>
					<Titles></Titles>
					<SearchBar clicks = {clicks} lists = {lists}
					onChangeMode={()=>clickc(styles.introduce_click)}
					onChangeList={()=>clists(styles.notscroller)}>
					</SearchBar>
					<PrintIcons click={clicks}></PrintIcons>
				</main>
			</a>
		</div>
	)
}
