import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>JG Homepage</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
				<a href="https://nextjs-six-kappa-95.vercel.app">Jaegeun</a>
				</h1>

				<div className={styles.introduce}>
					<div className={styles.scroller}>
						<span>
						안녕하세요. 저는 장재근입니다.<br/>
						AI 개발쪽을 꿈꾸고 있습니다.<br/>
						이게 저의 첫 홈페이지가 되겠군요 <br/>

						</span>
					</div>
				</div>
			</main>
		</div>
	)
}
