import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

function Headline(){
	return (
		<Head>
			<title>JG Homepage</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	)
}

function Titles() {
	return(
		<div className={styles.title}>
			<h1>Introduce</h1>
		</div>
	)
}

function Body(){
	return(
			<div className={styles.idx2body}>
				<a href="/">
					<Image src="/profile.png" alt="profile" width={250} height={250}></Image>
				</a>
				
				<p><b>Name</b></p>
				<p>Jang JaeGeun</p><br/>
				
				<p><b>Major</b></p>
				<p>Computer Science<br/>
				Mathematical Statistics</p><br/>
				
				<p><b>Language</b></p>
				<p>Python / C / C++ / JavaScript</p><br/>
				
				<p><b>FrameWork</b></p>
				<p>Tensorflow / Pytorch / React</p>
			</div>
	)
}

export default function Home() {
	return (
		<div className={styles.container}>
			<Headline></Headline>
				<main className={styles.main}>
					<Titles></Titles>
					<Body></Body>
				</main>
		</div>
	)
}
