import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JG Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
		  J<a href="https://github.com/JaeGeunJang">ae</a>Geun
        </h1>

        <p className={styles.description}>
          예비 AI 개발자 <br/>
		  <code className={styles.code}>Pytorch, Tensorflow</code>
		  잘쓰고 싶다
        </p>

		<div className={styles.description2}>
			현재 진행 중인 프로젝트
		</div>

        <div className={styles.grid}>
          <a href="https://jk-codingbeginner.tistory.com/" className={styles.card}>
            <h2>Tistory &rarr;</h2>
            <p>
			현재 진행하고 있는 프로젝트를 통해 배운 점들을 적습니다. <br/>
			이후 데이터 통계, AI 관련 내용도 올라올 예정입니다.
			</p>
          </a>

          <a href="https://github.com/JaeGeunJang/MiniProject" className={styles.card}>
            <h2>Toy Project &rarr;</h2>
            <p>
			가끔 (주로) 파이썬으로 후딱 짜보는 프로그램들<br/>
			물론 지금은 하나 밖에 없습니다.
			</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
